
services:
  kiro_rs:
    image: ubuntu/rust:1.84-25.04_edge
    container_name: kiro_rs
    ports:
      - "8990:8990"
    volumes:
      - .:/workspace    
    working_dir: /workspace

    environment:
      - REDIS_DB=0
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 512M
    restart: always
    entrypoint: ["/workspace/entrypoint.sh"]
