
services:
  claudecode_server:
    image: rust:1.92-alpine
    container_name: kiro_rs
    ports:
      - "8990:8990"
    volumes:
      - .:/workspace    
    working_dir: /workspace

    environment:
      - REDIS_DB=0
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    restart: always
    entrypoint: ["/workspace/entrypoint.sh"]
